### ISSUE TITLE
Updating this threeJS viewer for latest BIMserver

### ISSUE THREAD

**Issue by connoralexander** [opensourceBIM/WebGL-threeJS#12]
Hi,

So I am trying to use this threeJS viewer with the latest BIMserver, but looking through it I get the impression that each time the BIMserver has been updated, the source for the threeJS viewer needs updating too? I have attempted to get it to work but have so far failed.

Are you able to give me any indication regarding which code needs updating for this to work with the latest BIMserver (1.4.0 23Sep15)?

**Comment by rubendel** [comment]
I would suggest reading through the commit history. Is this threeJS viewer opensource? Then I could have a look at it.

**Comment by rubendel** [comment]
Oh haha nevermind, apparently I get notifications for this project

**Comment by rubendel** [comment]
Yeah this project has not been updated for more than 2 years, I wouldn't expect much of it to be honest

**Comment by hlg** [comment]
The plugin part may need updating upon BIMserver changes in the serializer plugin interface. In fact I have abandoned it a little bit since there didn't seem to be any interest in it.

**Comment by connoralexander** [comment]
Ok, yeah I saw this died a little bit! I intend to try and build on it with some new integrations so am really interested in continuing with the project

**Comment by rubendel** [comment]
Alright, well that's cool. From the top of my head what has changed in the last 2 years:
- Model data is loaded using the JSON serializer (I don't think you really need a specific serializer for ThreeJS)
- Geometry is now loaded in binary form
- WebSockets are used for the transmission of the geometry, mainly because it can be done streaming

That's at least how BIMvie.ws/BIMsurfer are doing it now. You can probably get quite far by looking at those code bases.

**Comment by hlg** [comment]
I have just updated what was there. It uses [three.js JSON format](https://github.com/mrdoob/three.js/wiki/JSON-Model-format-3) version 3 for the geometry. IFC object data is fetched with the getDataObjectByGuid method if needed. Switching to a more streamlined geometry transmission, as in BIMvie.ws/BIMsurfer is still open. The BIMserver code needs a patch for this to work, because JsonConverter provokes a NullpointerException by not setting the ProgressReporter.

**Comment by connoralexander** [comment]
Hi there,

I am having issues with installing this viewer, though the problem may be my misinterpretation of the previous issue response..

I am copying the jar file to the plugins folder inside the BIMserver but it is not being recognized from within the BIMviews/BIMserver plugins list. It does not come up in the plugins list, the web modules list or the render engines/serialisers...

I'm not sure if this is an error with the BIMserver? Or I need to restart a service to recognise it?

**Comment by hlg** [comment]
During testing I realized some irregularities with the recognition of enabled and disabled plugins. If so, this is a BIMserver issue. I'll check in detail and get back soon.

**Comment by connoralexander** [comment]
Hey, thanks for your efforts on this - I await your findings eagerly. If this is a BIMserver issue, I will open an issue on the correct repo

**Comment by connoralexander** [comment]
Hey, is there any update on this? I've been looking through the threeJS code but can't see why it wouldn't be recognised by BIMserver, so I have opened an issue on that repo too

**Comment by hlg** [comment]
If you restart the server the plugin is recognized. I do not know whether BIMserver checks for plugins at runtime and if so in which intervals, maybe you just have to wait a little. The issues I had seen where related to the `enabled` setting in `plugin.xml` and to removing a plugin from BIMserver. I will add my observations to the issue you opened for BIMserver.

**Comment by dlabz** [comment]
```
If I restart the server the plugin is recognized.
```
That's the expected behavior. I don't remember any BIMserver plugin being activated without restarting the BIMserver.

**Comment by rubendel** [comment]
Yes, that is right @dlabz, the main reason here being the fact that it's hard to unload classes, and the JVM gives no guarantees about it.
